name: check

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Hack container for local development
      if: ${{ env.ACT }}
      run: apt-get update && apt install -y nodejs
    - name: install git
      run: apt-get update && apt install -y git
    - name: Execute Pre-commit Hooks
      uses: pre-commit/action@v3.0.1
